version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
  daily-run-worflow:
    triggers:
      - schedule:
          corn: "40 4 * * 1-5"
          filters:
            branches:
              only: master
    jobs:
      - cypress/run:
