version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
  schedule-workflow:
    triggers:
      - schedule:
          corn: "15 15 * * 1,2,3,4,5,6"
          filters:
            branches:
              only: master
    jobs:
      - build
      - cypress/run
