version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          name: 'e2e_OLX-BH_functional-sanity'
          store_artifacts: true
          
  daily-run-workflow:
    triggers:
      - schedule:
          # Every day, at 5:35pm PK time.
          cron: "35 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress/run:
          name: 'e2e_scheduled_functional-sanity_OLX-BH'
          
